arm1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm1_joint
  pid: {p: 10.0, i: 0.01, d: 0.1}

arm2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm2_joint
  pid: {p: 10.0, i: 0.01, d: 0.1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
