# DWAPlannerROS Configuration

# Velocity limits for the robot
max_vel_x: 0.5
min_vel_x: 0.1
max_rotational_vel: 1.0
min_rotational_vel: 0.3

# Acceleration limits
acc_lim_x: 1.0
acc_lim_theta: 2.0

# Tolerances
xy_goal_tolerance: 0.3
yaw_goal_tolerance: 0.3
latch_xy_goal_tolerance: true

# Simulation time for DWA
sim_time: 4.0

# Number of samples for velocity and rotation
vx_samples: 20
vtheta_samples: 40

# Cost function weights
path_distance_bias: 32.0
goal_distance_bias: 24.0
occdist_scale: 0.3

# Forward point distance for DWA
forward_point_distance: 0.5

# Buffer and scaling
stop_time_buffer: 0.2
scaling_speed: 0.25
max_scaling_factor: 0.2
